"""Recommendations router — gap analysis only (LLM-based).

Old token-matching recommendation endpoints have been removed.
Role matching is now done via LLM in profiles._llm_match_role.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from backend.auth import get_current_user
from backend.db import get_db
from backend.models import Profile, User
from backend.services.graph.matching import find_role_id_for_job_target

logger = logging.getLogger(__name__)

router = APIRouter()

# ── Gap analysis DB cache helpers ─────────────────────────────────────────


def _load_gap_cache(profile: Profile, p_hash: str, role_id: str) -> dict | None:
    """Load cached gap analysis from DB for a specific role."""
    try:
        cached = json.loads(profile.cached_gaps_json or "{}")
    except (json.JSONDecodeError, TypeError):
        return None
    if cached.get("hash") != p_hash:
        return None
    return cached.get("roles", {}).get(role_id)


def _save_gap_cache(
    profile: Profile, p_hash: str, role_id: str, result: dict, db: Session
):
    """Persist gap analysis result to DB."""
    try:
        cached = json.loads(profile.cached_gaps_json or "{}")
    except (json.JSONDecodeError, TypeError):
        cached = {}
    if cached.get("hash") != p_hash:
        cached = {"hash": p_hash, "roles": {}}
    cached.setdefault("roles", {})[role_id] = result
    profile.cached_gaps_json = json.dumps(cached, ensure_ascii=False)
    db.commit()


# ── Role data loader (replaces SkillMatchService for role lookup) ─────────

_roles_data: dict[str, dict] | None = None


def _get_roles_data() -> dict[str, dict]:
    """Load roadmap_skills.json once."""
    global _roles_data
    if _roles_data is None:
        path = Path("data/roadmap_skills.json")
        with open(path, "r", encoding="utf-8") as f:
            _roles_data = json.load(f)
    return _roles_data


def _get_role(role_id: str) -> dict | None:
    """Get role data by ID."""
    return _get_roles_data().get(role_id)


def _ensure_job_target_first(
    profile_data: dict, recs: list[dict]
) -> tuple[list[dict], str]:
    """API-layer insurance: ensure job_target role ranks #1 with high affinity.

    Also attempts regex fallback on raw_text if job_target is missing from parsed data.
    Returns (modified_recs, job_target_source) for diagnostics.
    """

    job_target = (profile_data.get("job_target") or "").strip()
    source = "parsed"

    # Fallback: extract from raw_text if parsed job_target is empty
    if not job_target:
        raw_text = (profile_data.get("raw_text") or "").strip()
        if raw_text:
            import re as _re

            for pat in [
                r"(?:求职意向|期望职位|求职目标|意向岗位|期望岗位|目标职位|应聘职位)\s*[：:]\s*([^\n\r]{1,40})",
                r"(?:求职意向|期望职位|求职目标|意向岗位|期望岗位|目标职位|应聘职位)\s+([^\n\r]{1,40})",
            ]:
                m = _re.search(pat, raw_text, _re.IGNORECASE)
                if m:
                    jt = m.group(1).strip()
                    jt = _re.sub(r"[\s,，;.；。]+$", "", jt)
                    if jt and jt not in {"面议", "不限", "待定", "无", "—", "-", "/"}:
                        job_target = jt
                        source = "raw_text_fallback"
                        break

    if not job_target or job_target in {"未指定", "面议", "不限", "待定", "无"}:
        return recs, f"empty ({source})"

    from backend.services._shared.recommendations import apply_job_target_override
    from backend.services.graph.query import get_graph_nodes

    graph_nodes = get_graph_nodes()
    recs = apply_job_target_override(
        recs, job_target, graph_nodes, min_affinity=88, boost_above_top=True
    )
    target_role_id = find_role_id_for_job_target(job_target)
    return recs, f"boosted: {job_target} -> {target_role_id}"


def _save_rec_cache(profile: Profile, p_hash: str, resp: dict, db: Session):
    """Persist recommendations to DB."""
    profile.cached_recs_json = json.dumps(
        {"hash": p_hash, "data": resp}, ensure_ascii=False
    )
    db.commit()


@router.get("")
def get_recommendations_endpoint(
    top_k: int = Query(5, ge=1, le=10),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Get recommendations — always reads cached_recs_json (single source of truth).

    Recommendations are generated by the background thread (_auto_locate_on_graph)
    after profile creation/update. This endpoint only reads the cache.
    If no cache exists yet (background thread still running), returns empty list.
    """
    profile = db.query(Profile).filter(Profile.user_id == user.id).first()
    if not profile:
        return {"recommendations": [], "user_skill_count": 0}

    db.refresh(profile)
    try:
        cached = json.loads(profile.cached_recs_json or "{}")
        data = cached.get("data")
        if data and data.get("recommendations"):
            profile_data = json.loads(profile.profile_json or "{}")
            recs, jt_diag = _ensure_job_target_first(
                profile_data, data["recommendations"]
            )
            data["recommendations"] = recs[:top_k]
            data["_job_target"] = profile_data.get("job_target", "")
            data["_jt_diag"] = jt_diag  # diagnostic
            logger.info(
                "[GET-REC] job_target=%r diag=%s top_rec=%r",
                profile_data.get("job_target"),
                jt_diag,
                recs[0]["label"] if recs else "none",
            )
            return data
    except (json.JSONDecodeError, TypeError):
        pass

    return {"recommendations": [], "user_skill_count": 0}


# ── Gap analysis detail (for MatchDetailPage) ─────────────────────────────


@router.get("/match-analysis/{role_id}")
def get_match_analysis_detail(
    role_id: str,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Get full LLM gap analysis detail for a specific role (DB-cached)."""
    from backend.services.gap_analyzer import analyze_gaps, profile_hash

    profile = db.query(Profile).filter(Profile.user_id == user.id).first()
    if not profile:
        raise HTTPException(404, "请先建立画像")

    profile_data = json.loads(profile.profile_json or "{}")
    p_hash = profile_hash(profile_data)

    role = _get_role(role_id)
    if not role:
        raise HTTPException(404, "角色不存在")

    role_label = role.get("label", role_id)

    # DB cache check
    cached = _load_gap_cache(profile, p_hash, role_id)
    if cached:
        cached["label"] = role_label
        return cached

    topics = role.get("topics", [])
    if not topics:
        topics = role.get("must_skills", [])

    result = analyze_gaps(profile_data, role_id, role_label, topics)
    result["label"] = role_label
    if not result.get("failed"):
        _save_gap_cache(profile, p_hash, role_id, result, db)
    return result


# ── Confirm mastered module ────────────────────────────────────────────────
