import type { ProfileData } from '@/types/profile'

export const mockProfileData: ProfileData = {
  id: 1,
  name: '小林',
  source: 'resume',
  created_at: '2026-03-10T08:00:00',
  updated_at: '2026-04-12T10:30:00',
  profile: {
    education: { school: '杭州电子科技大学', major: '计算机科学与技术', degree: '本科' },
    experience_years: 0,
    skills: [
      { name: 'Python', level: 'proficient' },
      { name: 'React', level: 'familiar' },
      { name: 'SQL', level: 'familiar' },
      { name: 'LangChain', level: 'beginner' },
    ],
    knowledge_areas: ['机器学习', 'Web开发', '数据库'],
    internships: [
      {
        company: '某互联网公司',
        role: '后端开发实习生',
        duration: '2024.07 - 2024.09',
        tech_stack: ['Python', 'FastAPI', 'PostgreSQL'],
        highlights: '参与推荐系统接口优化，响应时间下降 30%',
      },
    ],
    projects: [
      {
        name: '校园二手交易平台',
        description: '一个帮助校内学生交易闲置物品的微信小程序，负责后端架构和支付对接。',
        tech_stack: ['Node.js', 'MongoDB', '微信小程序'],
      },
      {
        name: '个人博客系统',
        description: '用 Next.js 搭建的 Markdown 博客，支持暗色模式和 ISR 渲染。',
        tech_stack: ['Next.js', 'TailwindCSS'],
      },
    ],
    soft_skills: {
      _version: 2,
      communication: { score: 72, level: 'medium', advice: '你在团队讨论里是那种先听再说的人，话不多但准。' },
      learning: { score: 85, level: 'high', advice: '遇到新技术时，你习惯先跑通一个最小 Demo，再回头看文档。' },
      collaboration: { score: 68, level: 'medium', advice: '你更倾向于独立完成模块，但在需要时也能配合别人接口。' },
      innovation: { score: 60, level: 'medium', advice: '你的项目偏向实用主义，能把现有工具组合出好效果。' },
      resilience: { score: 70, level: 'medium', advice: ' deadline 临近时你会优先保证交付，而不是追求完美。' },
    },
    certificates: ['CET-6', '普通话二级甲等'],
    awards: ['数学建模省三等奖'],
    job_target: '',
  },
  quality: {},
  graph_position: {
    from_node_id: 'backend-engineer',
    from_node_label: '后端开发工程师',
    target_node_id: 'ai-engineer',
    target_label: 'AI 工程师',
    target_zone: 'transition',
    gap_skills: ['PyTorch', '深度学习', 'LLM 微调'],
    total_hours: 320,
    safety_gain: 0.35,
    salary_p50: 18000,
  },
  career_goals: [
    {
      id: 1,
      target_node_id: 'ai-engineer',
      target_label: 'AI 工程师',
      target_zone: 'transition',
      from_node_id: 'backend-engineer',
      from_node_label: '后端开发工程师',
      gap_skills: ['PyTorch', '深度学习', 'LLM 微调'],
      total_hours: 320,
      safety_gain: 0.35,
      salary_p50: 18000,
      is_primary: true,
      set_at: '2026-04-01T10:00:00',
    },
  ],
}
